package pl.company.settlements.file.domain;

public enum AttachmentType {
    CONTRACT,
    AMENDMENT,
    MAIN_CONTRACTOR_INVOICE,
    SUBCONTRACTOR_INVOICE,
    PAYMENT_CONFIRMATION,
    SUBCONTRACTOR_STATEMENT,
    ACCEPTANCE_PROTOCOL,
    NECESSITY_PROTOCOL,
    WORK_PROGRESS_REPORT
}
